BaiCuoiKy/TestUngDung/Areas/Admin/Controllers/CustomerController.cs
using ModelEF.Dao;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace TestUngDung.Areas.Admin.Controllers
{
    public class CustomerController : Controller
    {
        // GET: Admin/Customer
        public ActionResult Index(string searchString, int page = 1, int pagesize = 5)
        {
            var customer = new CustomerDao();
            var model = customer.ListWhereAll(searchString, page, pagesize);
            ViewBag.searchString = searchString;
            return View(model);
        }
    }
}

BaiCuoiKy/TestUngDung/Areas/Admin/Controllers/ProductController.cs
using ModelEF.Dao;
using ModelEF.Model;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace TestUngDung.Areas.Admin.Controllers
{
    public class ProductController : BaseController
    {
        // GET: Admin/Product

        HoangMinhContext db = new HoangMinhContext();
        public ActionResult Index(string searchString)
        {
            var product = new ProductDao();
            var model = product.ListWhereAll(searchString);
            ViewBag.searchString = searchString;
            return View(model);
        }
        [HttpGet]
        public ActionResult Create()
        {
            setViewBag();
            return View();
        }
        public void setViewBag(int? selectedID = null)
        {
            var dao = new CategoryDao();
            ViewBag.category_id = new SelectList(dao.ListAll(), "category_id", "category_name", selectedID);
        }
    
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Product sp, HttpPostedFileBase product_image)
        {


            if (product_image != null && product_image.ContentLength > 0)
            {
                //int id = int.Parse(db.Product.ToList().Last().product_id.ToString());

                string _FileName = Path.GetFileName(product_image.FileName);
                //int index = Path.GetFileName(product_image.FileName).IndexOf('.');
                //_FileName = "sp" + id.ToString() + "." + Path.GetFileName(product_image.FileName).Substring(index + 1);

                string _path = Path.Combine(Server.MapPath("~/Upload/sanpham/" + _FileName));
                product_image.SaveAs(_path);

                sp.product_image = _FileName;

            }

            if (ModelState.IsValid)
            {
                db.Product.Add(sp);
                db.SaveChanges();
                SetAlert("Thêm Sản Phẩm Thành Công", "success");
                return RedirectToAction("Index");
            }
            //setViewBag();
            return View();
        }
        [HttpGet]
        public ActionResult Edit(System.Int32 id)
        {
            var product = new ProductDao();
            var result = product.FindId(id);
            setViewBag(result.category_id);
            if (result != null)
                return View(result);
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Product sp, HttpPostedFileBase product_image)
        {
            Product unv = db.Product.FirstOrDefault(x => x.product_id == sp.product_id);

            if (unv != null)
            {
                unv.category_id = sp.category_id;
                unv.product_name = sp.product_name;
                unv.product_unicost = sp.product_unicost;
                unv.product_quantity = sp.product_quantity;
                unv.product_size = sp.product_size;
                unv.product_des = sp.product_des;
                unv.product_status = sp.product_status;
                if (product_image != null && product_image.ContentLength > 0)
                {
                    int id = sp.product_id;

                    string _FileName = "";
                    int index = Path.GetFileName(product_image.FileName).IndexOf('.');
                    _FileName = "udsp" + id.ToString() + "." + Path.GetFileName(product_image.FileName).Substring(index + 1);
                    string _path = Path.Combine(Server.MapPath("~/Upload/sanpham/" + _FileName));
                    product_image.SaveAs(_path);
                    unv.product_image = _FileName;
                }
            }

            if (ModelState.IsValid)
            {
                db.SaveChanges();
                SetAlert("Cập Nhật Sản Phẩm Thành Công", "success");
                return RedirectToAction("Index");
            }
            //setViewBag(sp.category_id);
            return View();
        }
        public JsonResult Delete(System.Int32 id)
        {

            var product = new ProductDao();
            bool re = product.Delete(id);
            return Json(re, JsonRequestBehavior.AllowGet);
        }
        public ActionResult Detail(System.Int32 id)
        {
            var product_detail = new ProductDetailDao();
            var model = product_detail.ListWhereAll(id);
            return View(model);
        }
    }
}

BaiCuoiKy/TestUngDung/Areas/Admin/Views/Shared/_Layout.cshtml
@using TestUngDung.Common;
@using TestUngDung.Areas.Admin.Models;
@{
    Layout = null;
}

<!DOCTYPE html>

<html lang="en">

<head>
    <meta charset="utf-8" />
    <link rel="apple-touch-icon" sizes="76x76" href="~/Assets/Admin/img/apple-icon.png">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <link rel="shortcut icon" href="~/Assets/Admin/img/favicon.png">
    <title>@ViewBag.Title</title>
    <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0, shrink-to-fit=no' name='viewport' />
    <!--     Fonts and icons     -->
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700,200" rel="stylesheet" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css" />
    <!-- CSS Files -->
    <link href="~/Assets/Admin/bs3/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote.min.css" rel="stylesheet">
    <link href=~/Assets/Admin/css/light-bootstrap-dashboard.css?v =2.0.0 " rel="stylesheet" />

    <!-- Data table -->
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.24/css/jquery.dataTables.css">
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/buttons/1.7.0/css/buttons.dataTables.min.css">
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@9"></script>
    <!-- CSS Just for demo purpose, don't include it in your project -->
    <link href="~/Assets/Admin/css/demo.css" rel="stylesheet" />
    <script src="~/Assets/Admin/js/Chart.min.js"></script>
</head>

<body>
    <div class="wrapper">
        <div class="sidebar" data-image="../assets/img/sidebar-5.jpg">
            <div class="sidebar-wrapper">
                <div class="logo">
                    <a href="@Url.Action("Index","Home")" class="simple-text">
                       <img src="~/Assets/Admin/img/admin_logo.png" alt=""/> ADMIN
                    </a>
                </div>
                <ul class="nav">
                    <li class="nav-item active">
                        <a class="nav-link" href="@Url.Action("Index","Home")">
                            <i class="nc-icon nc-chart-pie-35"></i>
                            <p>Điều Khiển</p>
                        </a>
                    </li>
                    <li>
                        <a class="nav-link" href="@Url.Action("Index","User")">
                            <i class="nc-icon nc-circle-09"></i>
                            <p>Thông Tin Người Dùng</p>
                        </a>
                    </li>
                    <li>
                        <a class="nav-link" href="@Url.Action("Index","Category")">
                            <i class="fa fa-align-center"></i>
                            <p>Quản Lý Danh Mục</p>
                        </a>
                    </li>
                    <li>
                        <a class="nav-link" href="@Url.Action("Index","Product")">
                            <i class="fa fa-apple"></i>
                            <p>Quản Lý Sản Phẩm</p>
                        </a>
                    </li>
                    <li>
                        <a class="nav-link" href="@Url.Action("Index","Customer")">
                            <i class="fa fa-user-md"></i>
                            <p>Khách Hàng</p>
                        </a>
                    </li>
                </ul>
            </div>
        </div>
        <div class="main-panel">
            <!-- Navbar -->
            <nav class="navbar navbar-expand-lg " color-on-scroll="500">
                <div class="container-fluid d-flex">
                    <a class="navbar-brand" href="#pablo"> Điều Khiển </a>
                    <div class="collapse navbar-collapse justify-content-end" id="navigation">
                        <ul class="nav navbar-nav mr-auto">
                            <li class="nav-item">
                                <a href="#" class="nav-link" data-toggle="dropdown" style="line-height:15px">
                                    <i class="nc-icon nc-palette" style="margin-top:0px;margin-right: 5px;"></i>
                                    <span class="d-lg-none">Điều Khiển</span>
                                </a>
                            </li>
                            <li class="dropdown nav-item">
                                <a href="#" class="dropdown-toggle nav-link" data-toggle="dropdown" style="line-height:15px">
                                    <i class="nc-icon nc-planet" style="margin-top:0px;"></i>
                                </a>
                            </li>
                            <li class="nav-item">
                                <a href="#" class="nav-link" style="line-height:15px">
                                    <i class="nc-icon nc-zoom-split" style="margin-top:0px"></i>
                                    <span class="d-lg-block">&nbsp;Tìm Kiếm</span>
                                </a>
                            </li>
                        </ul>
                        <ul class="navbar-nav ml-auto">
                            <li class="nav-item">
                                <a class="nav-link" href="#pablo" style="line-height:15px">
                                    <span class="no-icon">
                                        @{
                                            var session = (LoginModel)Session[Constants.USER_SESSION];
                                        }
                                        @if (session != null)
                                        {@session.username}
                                    </span>
                                </a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link" href="@Url.Action("Logout","Home")" style="padding:0px;">
                                    <span class="no-icon"><i class="fa fa-sign-out"></i>&nbsp;Đăng Xuất</span>
                                </a>
                            </li>
                        </ul>
                    </div>
                </div>
            </nav>
            <!-- End Navbar -->
            <div class="content">
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-lg-12">
                            <header class="panel-heading">
                                <label style="color:blueviolet;"><b>@RenderSection("header", required: true)</b></label>
                            </header>
                            <div class="panel-body" style="background: #fff;font-family: cursive;">
                                @if (TempData["AlertMessage"] != null)
                                {
                                    <div id="AlertBox" class="alert @TempData["AlertType"] hide">
                                        @TempData["AlertMessage"]
                                    </div>
                                }
                                @RenderBody()
                            </div>
                        </div>

                    </div>
                </div>
            </div>
            <footer class="footer">
                <div class="container-fluid">
                    <nav>
                        <ul class="footer-menu">
                            <li>
                                <a href="@Url.Action("Index","Home")">
                                    Trang Chủ
                                </a>
                            </li>
                            <li>
                                <a href="@Url.Action("Index","User")">
                                    Người Dùng
                                </a>
                            </li>
                            <li>
                                <a href="@Url.Action("Index","Category")">
                                    Danh Mục
                                </a>
                            </li>
                            <li>
                                <a href="@Url.Action("Index","Product")">
                                    Sản Phẩm
                                </a>
                            </li>
                            <li>
                                <a href="@Url.Action("Index","Customer")">
                                    Khách Hàng
                                </a>
                            </li>
                        </ul>
                        <p class="copyright text-center">
                            ©
                            <script>
                                document.write(new Date().getFullYear())
                            </script>
                            <a href="http://www.creative-tim.com">Hoàng Minh</a>, made with love for a better web
                        </p>
                    </nav>
                </div>
            </footer>
        </div>
    </div>

</body>
<!--   Core JS Files   -->
<script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
<script src="~/Assets/Admin/js/core/popper.min.js" type="text/javascript"></script>
<!--<script src="~/Assets/Admin/js/core/bootstrap.min.js" type="text/javascript"></script>-->
<script src="~/Assets/Admin/bs3/js/bootstrap.min.js"></script>
<!--  Plugin for Switches, full documentation here: http://www.jque.re/plugins/version3/bootstrap.switch/ -->
<script src="~/Assets/Admin/js/plugins/bootstrap-switch.js"></script>
<!--  Google Maps Plugin    -->
<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=YOUR_KEY_HERE"></script>
<!--  Chartist Plugin  -->
<script src="~/Assets/Admin/js/plugins/chartist.min.js"></script>
<!--  Notifications Plugin    -->
<script src="~/Assets/Admin/js/plugins/bootstrap-notify.js"></script>
<!-- Control Center for Light Bootstrap Dashboard: scripts for the example pages etc -->
<script src="~/Assets/Admin/js/light-bootstrap-dashboard.js?v=2.0.0 " type="text/javascript"></script>
<!-- Light Bootstrap Dashboard DEMO methods, don't include it in your project! -->
<script src="~/Assets/Admin/js/demo.js"></script>
<script src="~/Scripts/jquery.unobtrusive-ajax.js"></script>
<script>
    $('#AlertBox').removeClass("hide");
    $('#AlertBox').delay(1500).slideUp(700);
</script>
<script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.24/js/jquery.dataTables.js"></script>
@Scripts.Render("~/bundles/jquery")
@Scripts.Render("~/bundles/bootstrap")
<script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
<script src="https://cdn.datatables.net/1.10.24/js/jquery.dataTables.min.js" crossorigin="anonymous"></script>
<script src="https://cdn.datatables.net/1.10.20/js/dataTables.bootstrap4.min.js" crossorigin="anonymous"></script>
<script src="~/Scripts/jquery.unobtrusive-ajax.js"></script>
<script type="text/javascript">
    $('#myTable').DataTable({
        "aLengthMenu": [[5, 10, 15, -1], [5, 10, 15, "Tất Cả"]],
        "iDisplayLength": 5,   
        "language": {
            "sLengthMenu": "Hiển thị _MENU_ dòng trên 1 trang",
            "sZeroRecords": "Không tìm thấy dữ liệu",
            "info": "Hiển thị trang _PAGE_ trong tổng số _PAGES_ trang",
            "sInfoEmpty": "Không có dữ liệu nào",
            "sInfoFiltered": "(được lọc từ tổng sô _MAX_ trong dữ liệu)",
            "sSearch": "Tìm kiếm:",
            "sShow": "Hiển Thị:",
            "oPaginate": {
                "sNext": "Sau",
                "sPrevious": "Trước"
            },
        }
    });
</script>
<script type="text/javascript">
    $(document).ready(function () {
        $('#myTable').DataTable();
    });
</script>
@RenderSection("scripts", required: false)

</html>